### ISSUE TITLE
FOSRestBundle incompatibility

### ISSUE THREAD

**Issue by mnapoli** [PHP-DI/Symfony2-Bridge#1]
See: https://github.com/FriendsOfSymfony/FOSRestBundle/issues/604

When defining a route with FOSRestBundle, for example:

``` yaml
notification:
    type:     rest
    resource: Missive\ApiBundle\Controller\NotificationController
```

FOSRestBundle will **not** call the container to get the controller if `resource:` is a class name. That's a problem with PHP-DI: it forces to define a container entry with a custom name for each controller.
